server:  
  port: ${EUREKA_SERVER_PORT:1111}   # HTTP port
#Eureka Config
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
    
logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservices: 'DEBUG'





