server:
  port: 8761
  
spring:
  profiles.default: default
---
spring:
  profiles: default
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    com.microservices: DEBUG
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: docker
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/