server:
  port: 8761
#Eureka Config
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    

spring:
  # Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
  profiles: docker
    eureka:
      instance:
        hostname: docker
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
 
logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservices: 'DEBUG'





