server:
  port: 8763
  
spring:
  profiles.default: default
---
spring:
    profiles: default
    # Datasource and JPA configuration to be used for storing the OAuth authorization details 
    # and token store
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:testdb;MODE=MySQL;MV_STORE=FALSE;MVCC=FALSE
        username: sa
        driver-class: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
rabbitmq:
  host: localhost
  username: guest
  password: guest
  alternate-exchange:
    name: users_alt.fanout
    queue: users_alt
  deadletters-exchange:
    name: deadletters.fanout
    queue: deadletters
  admin-exchange:
    name: admin.topic
    queues:
      users:
        name: users_manadgement
        routing-key: admin.user

swagger:
  group-name: notifications
  path-mapping: /
  api-info:
    title: Notification Module
    description: notification-web application provides a REST API for get notifications
    version: 0.0.1-SNAPSHOT
    license: Open source licensing
    license-url: https://help.github.com/articles/open-source-licensing/
