server:
  port: 8763
  
spring:
  profiles.default: default
---
spring:
  profiles: default
rabbitmq:
  host: localhost
  username: guest
  password: guest
  alternate-exchange:
    name: users_alt.fanout
    queue: users_alt
  deadletters-exchange:
    name: deadletters.fanout
    queue: deadletters