server:
  port: 8761
  
spring:
  profiles.default: default
---
spring:
  profiles: default
rabbitMQConfig:
  alternateExchangeName: users_alt.fanout
  alternateQueueName: users_alt
  brokerHost: localhost
  brokerUsername: guest
  brokerPassword: guest