spring:
    cloud:
        stream:
            default:
                contentType: application/json
            bindings:
                userNotifications:
                    destination: users.direct
                    binder: rabbit1
            rabbit:
                bindings:
                    userNotifications:
                        producer:
                            exchangeType: direct
                            routingKeyExpression: 'requestMessage.userId'
                            declareExchange: false
            binders:
                rabbit1:
                    type: rabbit
                    environment:
                        spring:
                            rabbitmq:
                                host: localhost
                                port: 5672
                                username: guest
                                password: guest
                                virtual-host: /