spring:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  # Datasource and JPA configuration to be used for storing the OAuth authorization details 
  # and token store
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql-service/auth
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      driver-class: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
# LDAP configuration
ldap:
  uri: ldap://192.168.1.1:389/dc=bisite,dc=net
  admin-DN: cn=admin,dc=bisite,dc=net
  admin-password: '{cipher}AgCVpSWVbyV7iPn8DdW/q01qnyYZtRY9mteyWjXn4bmspIXwVZSoFDnDhymEVGsNSt2BOJegRv9lz01wREFvA1PYL5vdQkyHyI8atveSjGqW0uIPNbWzvDor/9K5hxl41RiW2t+YncPNPjTWNU7Rm3EtF/RljacwjwqLpzDCjMOOPISZyQOw6nZ7iKUOGaUpZQySAZ8xbanwNMY1V3mWGBW5KB45phoykpIJC7+HP0mtCi9Y3IFotOtyFii62O19r8cfUwmp1UIcwN4HHn7cRlwXKxu9S6fmboy4/s9K1SZlUwMk4jGWRXfHHjNcBZzzXeBP8eGZ4OtOPcxpmxfZ8xA8Aob6+GTCH5+l019ujHcfbzRtgZEtUUlHXTVR94AQKR0GhZ8WfR/oULXlL307F7/jqwnkyeFkHspINqDk5ev13i5hmSMHnTwahRqxGVMVwqhy1wlE2mi/IaSHpZVuVlNeGbH2VNSqSxPUhCJQ9XlUEIt7O/C7UrD/NfVP7qwWrJnoc4LGttuVVRu8USGd4ZC1QqpixozGqHOHn4P1dk/gLNkGZaVLAt4JlSNyetRs8StjGOzYSKQ3Gd/6X5p/2ip8By2tAAta5ikXGNK8O5DkbmHAoGsu3rJgGpdMhOrC355iaI3YYnUfghMFPrfBS7bgD8MA1aNqhnDZTwX4aJSdfW7Niv6oo+Y0+Cd9YVUBMfB5phRXZc6cL3+ltbN303rU'
  search-base: ou=users
  search-filter: uid={0}
  group-search-base: ou=groups
  group-search-filter: memberUid={1}
  group-role-attribute: cn
