spring:
  profiles: docker
# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://mysql-service/auth
  username: root
  password: root
  hikari:
    data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  driver-class: com.mysql.jdbc.Driver
jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false